import Vue from 'vue'
import { MLInstaller, MLCreate, MLanguage } from 'vue-multilanguage'

Vue.use(MLInstaller)

export default new MLCreate({
    initial: 'ru',
    save: process.env.NODE_ENV === 'production',
    languages: [
        new MLanguage('ru').create({
            callBack: 'Заказать&nbsp;звонок',
            title: 'Продадим вашу компанию <br>по лучшей стоимости <br>в&nbsp;Казахстане',
            subtitle: 'Ответьте на&nbsp;вопросы и&nbsp;мы найдём покупателя на&nbsp;вашу компанию',
            btn: 'Получить стоимость',
            btn_send: 'Отправить компанию на продажу',
            site_link: 'Перейти на сайт',
            header_step: 'Вопрос {0}',
            header_step_cont: 'Контакты',
            header_thank: 'Спасибо',
            header_title_1: 'Номер БИН компании',
            header_title_2: 'Наличие лицензии',
            header_title_3: 'Лицензия в сфере',
            header_title_4: 'Наличие подтверждённого опыта работ',
            header_title_5: 'Наличие оборотов по расчетному счёту',
            header_title_6: 'Режим налогооблажения',
            header_title_7: 'Наличие архива первичной документации и 1С',
            header_title_8: 'Наличие ПКО Самрук-Казына',
            header_title_9: 'Наличие ПКО Государственные закупки',
            header_title_10: 'Стоимость продажи',
            header_title_11: 'Отправьте компанию на продажу',
            opt2_1: 'Есть лицензия',
            opt2_2: 'Нет лицензии',
            opt3_1: 'Строительства',
            opt3_2: 'Производства горных работ',
            opt3_3: 'Нефти и газа',
            opt3_4: 'Другое',
            opt4_1: 'От 1 до 5 лет',
            opt4_2: 'От 5 до 10 лет',
            opt4_3: 'Нет опыта',
            opt4_4: 'Другое',
            opt5_1: 'От 1 до 3 лет',
            opt5_2: 'От 3 до 5 лет',
            opt5_3: 'Нет оборотов',
            opt5_4: 'Другое',
            opt6_1: 'Общеустановленный',
            opt6_2: 'Упрощённый',
            opt6_3: 'Не знаю',
            opt7_1: 'Есть архив',
            opt7_2: 'Нет архива',
            opt7_3: 'Только 1С',
            opt7_4: 'Только бумажный архив',
            opt8_1: 'Есть',
            opt8_2: 'Нет',
            opt8_3: 'Не знаю',
            opt9_1: 'Есть',
            opt9_2: 'Нет',
            opt9_3: 'Не знаю',
            opt10_1: 'Ввердите сумму в тенге',
            opt11_label_1: 'Выберите предпочитаемые способы связи',
            opt11_label_2: 'Введите номер телефона и&nbsp;покупатель свяжется с&nbsp;вами в&nbsp;ближайшее время',
            opt11_1: 'Звонок',
            opt11_2: 'WhatsApp',
            opt11_3: 'СМС',
            alert_bin: 'Некорректный БИН',
            alert_phone: 'Некорректно введен телефон',
            alert_text: 'Введите значеине или пропустите данный шаг',
            alert_select: 'Выберите значеине или пропустите данный шаг',
            yes: 'Да',
            no: 'Нет',
            next: 'Далее →',
            final_text: 'Введите номер телефона и&nbsp;получите расчёт&nbsp;на WhatsApp и&nbsp;СМС <br>в&nbsp;течение <span class="mark">5 минут.</span>',
            alarm: 'Оставляя контактную информацию, вы соглашаетесь на обработку персональных данных',
            thanks_subtitle: 'Спасибо!',
            thanks_title: 'Ваша заявка принята',
            thanks_link: 'Скачать файл',
            modal_title: 'Заказать&nbsp;звонок',
            modal_intro: 'Заполните форму и&nbsp;мы свяжемся с&nbsp;вами в&nbsp;течение <span class="mark">5&nbsp;минут.</span>',
            send: 'Отправить',
            title_send: 'Cпасибо, заявка отправлена'
        }),
        new MLanguage('en').create({
            callBack: 'Order a call',
            title: 'Company formation in&nbsp;Kazakhstan',
            subtitle: 'Discover questionnaire and get a&nbsp;detailed cost report and gift from &nbsp;in&nbsp;three simple steps',
            btn: 'Get personalized report and&nbsp;gift!',
            btn_send: 'Отправить компанию на продажу',
            site_link: 'Visit website',
            header_step: 'Question {0}',
            header_step_cont: 'Контакты',
            header_thank: 'Thank you',
            header_title_1: 'Номер БИН компании',
            header_title_2: 'Наличие лицензии',
            header_title_3: 'Лицензия в сфере',
            header_title_4: 'Наличие подтверждённого опыта работ',
            header_title_5: 'Наличие оборотов по расчетному счёту',
            header_title_6: 'Режим налогооблажения',
            header_title_7: 'Наличие архива первичной документации и 1С',
            header_title_8: 'Наличие ПКО Самрук-Казына',
            header_title_9: 'Наличие ПКО Государственные закупки',
            header_title_10: 'Стоимость продажи',
            header_title_11: 'Отправьте компанию на продажу',
            opt2_1: 'Есть лицензия',
            opt2_2: 'Нет лицензии',
            opt3_1: 'Строительства',
            opt3_2: 'Производства горных работ',
            opt3_3: 'Нефти и газа',
            opt3_4: 'Другое',
            opt4_1: 'От 1 до 5 лет',
            opt4_2: 'От 5 до 10 лет',
            opt4_3: 'Нет опыта',
            opt4_4: 'Другое',
            opt5_1: 'От 1 до 3 лет',
            opt5_2: 'От 3 до 5 лет',
            opt5_3: 'Нет оборотов',
            opt5_4: 'Другое',
            opt6_1: 'Общеустановленный',
            opt6_2: 'Упрощённый',
            opt6_3: 'Не знаю',
            opt7_1: 'Есть архив',
            opt7_2: 'Нет архива',
            opt7_3: 'Только 1С',
            opt7_4: 'Только бумажный архив',
            opt8_1: 'Есть',
            opt8_2: 'Нет',
            opt8_3: 'Не знаю',
            opt9_1: 'Есть',
            opt9_2: 'Нет',
            opt9_3: 'Не знаю',
            opt10_1: 'Ввердите сумму в тенге',
            opt11_label_1: 'Выберите предпочитаемые способы связи',
            opt11_label_2: 'Введите номер телефона и&nbsp;покупатель свяжется с&nbsp;вами в&nbsp;ближайшее время',
            opt11_1: 'Звонок',
            opt11_2: 'WhatsApp',
            opt11_3: 'СМС',
            alert_bin: 'Некорректный БИН',
            alert_phone: 'Некорректно введен телефон',
            alert_text: 'Введите значеине или пропустите данный шаг',
            alert_select: 'Выберите значеине или пропустите данный шаг',
            yes: 'Yes',
            no: 'No',
            next: 'Next →',
            final_text: 'Please enter your phone number and get a&nbsp;quote on&nbsp;WhatsApp or&nbsp;SMS within <span class="mark">5 minutes.</span>',
            alarm: 'By providing us with your contact details you agree for&nbsp;processing of&nbsp;your personal data',
            thanks_subtitle: 'Thank you!',
            thanks_title: 'Your application is accepted',
            thanks_link: 'Download',
            modal_intro: 'Fill out the form and&nbsp;we will contact you within <span class="mark">5&nbsp;minutes.</span>',
            send: 'Send',
            title_send: 'Thank you, the&nbsp;application has been sent'
        })
    ]
})